In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\USER\Desktop\碩論\程式碼\embedding_data.csv")

data

,X2,X3,X1,Y
0,255.000000,94.940954,162.097863,4.686122
1,215.309400,130.434396,131.702366,4.410815
2,188.692556,112.414072,176.294826,3.444338
3,197.089163,155.840962,81.755694,3.378867
4,208.651847,70.102607,70.191431,3.135581
...,...,...,...,...
95,47.862764,55.539969,181.891681,-2.831205
96,56.421777,89.129206,191.903929,-3.037451
97,60.563777,24.069923,0.000000,-3.492096
98,86.754581,59.616503,135.187503,-3.672475


In [4]:
# 為了測試模型架構，先使用第一筆資料
test = data.iloc[0,:3]
y = data.iloc[0,3]

In [5]:
y = np.array(y) # 為了轉tensor，所以serious要轉成array

In [6]:
import torch

shape = (1,8) # 投影成8維，為了方便後續的attention計算

random = torch.randn(shape)

In [7]:
random # 先隨便猜

tensor([[-1.4027,  1.3003, -0.3341,  1.4626, -0.4955,  2.6081, -0.3305,  0.1952]])

In [8]:
test = torch.tensor(test, dtype = torch.float32) # tensor毛好多，統一設定dtype = float32
test = test.reshape(1,3)
test

C:\Users\USER\AppData\Local\Temp\ipykernel_23612\492316973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  test = torch.tensor(test, dtype = torch.float32) # tensor毛好多，統一設定dtype = float32


tensor([[255.0000,  94.9410, 162.0979]])

In [9]:
y = torch.tensor(y, dtype = torch.float32)
y

tensor(4.6861)

In [10]:
random = random.reshape(-1,1) # 為了後續矩陣乘法的需要
random

tensor([[-1.4027],
        [ 1.3003],
        [-0.3341],
        [ 1.4626],
        [-0.4955],
        [ 2.6081],
        [-0.3305],
        [ 0.1952]])

In [11]:
E =  random @ test # 將隨便猜的八維向量，根據原始的embedding縮放
E # 每個col是一個某個X，經過映射之後的新embedding

tensor([[-357.6931, -133.1754, -227.3776],
        [ 331.5817,  123.4537,  210.7791],
        [ -85.1870,  -31.7166,  -54.1515],
        [ 372.9568,  138.8583,  237.0804],
        [-126.3400,  -47.0386,  -80.3115],
        [ 665.0620,  247.6142,  422.7652],
        [ -84.2751,  -31.3771,  -53.5718],
        [  49.7869,   18.5365,   31.6485]])